name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Unzip Flutter project
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          unzip "$ZIP_FILE" -d flutter_project
          echo "PROJECT_DIR=$(find flutter_project -name pubspec.yaml -printf '%h\n' | head -n 1)" >> "$GITHUB_ENV"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          
      - name: Generate Android files
        run: flutter create . --platforms android
        working-directory: ${{ env.PROJECT_DIR }}
        
      - name: Install packages
        run: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Fix Dart number types
        run: |
          sed -i 's/unitPrice: unitPrice,/unitPrice: unitPrice.toDouble(),/' lib/services/parser_service.dart
          sed -i 's/totalWeight: totalWeight,/totalWeight: totalWeight.toDouble(),/' lib/services/parser_service.dart
          sed -i 's/value: value,/value: value.toDouble(),/' lib/services/parser_service.dart
        working-directory: ${{ env.PROJECT_DIR }}
        
      - name: Build APK
        run: flutter build apk --release
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ONP-Bulletin-APK
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
